import { ThemeOption } from './types';

export const lightThemes: ThemeOption[] = [
  {
    id: 'clean-slate',
    name: 'Clean Slate',
    type: 'light',
    colors: {
      background: '#FAFAFA',
      surface: '#F4F5F7',
      card: '#FFFFFF',
      cardBorder: '#E2E8F0',
      textPrimary: '#1A202C',
      textSecondary: '#4A5568',
      textMuted: '#A0AEC0',
      primary: '#3182CE',
      primaryLight: '#EBF8FF',
      accent: '#38B2AC',
      danger: '#E53E3E',
      dangerSurface: '#FFF5F5',
      success: '#48BB78',
      tabBar: '#FFFFFF',
      tabBarBorder: '#E2E8F0',
    },
  },
  {
    id: 'minimal-sage',
    name: 'Minimal Sage',
    type: 'light',
    colors: {
      background: '#F7FAF8',
      surface: '#EBF1ED',
      card: '#FFFFFF',
      cardBorder: '#D8E2DB',
      textPrimary: '#1C2921',
      textSecondary: '#415A4B',
      textMuted: '#8BA696',
      primary: '#2F855A',
      primaryLight: '#F0FFF4',
      accent: '#276749',
      danger: '#C53030',
      dangerSurface: '#FFF5F5',
      success: '#38A169',
      tabBar: '#FFFFFF',
      tabBarBorder: '#D8E2DB',
    },
  },
  {
    id: 'warm-amber',
    name: 'Warm Amber',
    type: 'light',
    colors: {
      background: '#FFFAF0',
      surface: '#FFF5E1',
      card: '#FFFFFF',
      cardBorder: '#FBD38D',
      textPrimary: '#4A3219',
      textSecondary: '#7B5A3A',
      textMuted: '#B79471',
      primary: '#DD6B20',
      primaryLight: '#FFFAF0',
      accent: '#C05621',
      danger: '#E53E3E',
      dangerSurface: '#FFF5F5',
      success: '#38A169',
      tabBar: '#FFFFFF',
      tabBarBorder: '#FBD38D',
    },
  },
];

export const darkThemes: ThemeOption[] = [
  {
    id: 'pure-oled',
    name: 'Pure OLED',
    type: 'dark',
    colors: {
      background: '#000000',
      surface: '#111111',
      card: '#0A0A0A',
      cardBorder: '#333333',
      textPrimary: '#FFFFFF',
      textSecondary: '#A0AEC0',
      textMuted: '#718096',
      primary: '#63B3ED',
      primaryLight: '#2A4365',
      accent: '#4FD1C5',
      danger: '#FC8181',
      dangerSurface: '#4A1D1D',
      success: '#68D391',
      tabBar: '#000000',
      tabBarBorder: '#333333',
    },
  },
  {
    id: 'midnight-navy',
    name: 'Midnight Navy',
    type: 'dark',
    colors: {
      background: '#0B132B',
      surface: '#122047',
      card: '#1C2541',
      cardBorder: '#273456',
      textPrimary: '#E2E8F0',
      textSecondary: '#A0AEC0',
      textMuted: '#4A5568',
      primary: '#4299E1',
      primaryLight: '#1A365D',
      accent: '#0BC9CD',
      danger: '#F56565',
      dangerSurface: '#541A1A',
      success: '#48BB78',
      tabBar: '#0B132B',
      tabBarBorder: '#273456',
    },
  },
  {
    id: 'charcoal-slate',
    name: 'Charcoal Slate',
    type: 'dark',
    colors: {
      background: '#121820',
      surface: '#1A232E',
      card: '#1F2A38',
      cardBorder: '#2D3B4E',
      textPrimary: '#EDF2F7',
      textSecondary: '#A0AEC0',
      textMuted: '#4A5568',
      primary: '#90CDF4',
      primaryLight: '#2C5282',
      accent: '#A0AEC0',
      danger: '#F56565',
      dangerSurface: '#541A1A',
      success: '#68D391',
      tabBar: '#121820',
      tabBarBorder: '#2D3B4E',
    },
  },
];
